name: Code Coverage

on: [pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Coveralls
    runs-on: ubuntu-latest
            
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure
        run: mkdir build && cd build && cmake .. -DCOVERAGE=ON
      - name: Build unit tests
        run: cmake --build build
      - name: Run tests
        run: cmake --build build --target test
      - name: Generate coverage .info
        run: cmake --build build --target coverage_report
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/lcov.info
