name: SerDe Test

on:
  workflow_dispatch:

jobs:
  build:
    name: SerDe Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Java
        uses: actions/checkout@v3
        with:
          repository: AlexanderSaydakov/datasketches-java
          path: java
      - name: Run Java
        run: cd java && mvn test
      - name: Run cmake
        run: cd build && cmake .. -DSERDE_COMPAT=true
      - name: Build C++ unit tests
        run: cmake --build build --config Release
      - name: Run C++ tests
        run: cmake --build build --config Release --target test
      - name: List files
        run: find .
